function DemoTutor()
  println("       AccurateSleep commands          ")
  println("----- commands -----------------------  :  ------------------------------------------")
  println("using AccurateSleep                     : loads AccurateSleep and exports sleep_ns")
  println("   do first before other commands       :")
  println("sleep_ns(SleepSec::AbstractFloat)       : sleeps specified seconds")
  println("   sleep_ns(.5)                         : sleeps half second")
  println("   sleep_ns(.000005)                    : sleeps 5 microseconds")
  println("AccurateSleep.DemoTutor()               : runs this tutorial")
  println("AccurateSleep.Demo1()                   : runs simple sample")
  println("AccurateSleep.Demo2(SleepSecs, )        : runs CDF report")
  println("AccurateSleep.Demo3(secs, DesiredSleep) : runs CPU utilizations simulation")
  println("  enter your command")
end
