function DemoTutor()
  println("       AccurateSleep commands          ")
  println("----- commands -----------------------  :  ------------------------------------------")
  println("AccurateSleep.DemoTutor()               : runs this tutorial")
  println("")
  println("using AccurateSleep                     : loads AccurateSleep and exports sleep_ns")
  println(" ... do 1st before any of following commands")
  println("")
  println("sleep_ns(SleepSecs::AbstractFloat)")
  println(" ... accurately sleeps number of SleepSecs ...")
  println(" sleep_ns(.5)                         : sleeps half second")
  println(" sleep_ns(.000005)                    : sleeps 5 microseconds")
  println(" sleep_ns(5.)                         : sleeps 5 seconds")
  println(" sleep_ns(1)                          : errors out - not float")
  println("")
  println("AccurateSleep.Demo1()                   : runs simple sample")
  println("")
  println("AccurateSleep.Demo2(SleepSecs::AbstractFloat, NumCycles::Integer, NumIters::Integer) ")
  println("...produces a detailed CDF report...")
  println("   AccurateSleep.Demo2(.001, 3, 2000)      - sleeps .001 secs over 3 cycles and 2000 iters")
  println("   AccurateSleep.Demo2(.000001, 3, 10000)  - sleeps .000001 microsecs over 3 cycles and 10000 iters")
  println("")
  println("AccurateSleep.Demo3(secs, DesiredSleep) : runs CPU utilizations simulation")
  println("  enter your command")
end
