function DemoTutor()
  println("       commands to run in REPL or your application      ")
  println("----- commands -----------------------  :  ------------------------------------------")
  println("using AccurateSleep                     : initializes and exports sleep_ns")
  println("sleep_ns(SleepSeconds::AbstractFloat)   : sleeps for specified seconds")
  println("AccurateSleep.DemoTutor()               : runs this tutorial")
  println("AccurateSleep.Demo1()                   : runs simple sample")
  println("AccurateSleep.Demo2()                   : runs CDF report")
  println("AccurateSleep.Demo3(secs, DesiredSleep) : runs CPU utilizations simulation")
  println("  enter your command")
end
